const STATUS_CODES={
    NOT_FOUND:404,
    ERROR_ARGUMENTOS:400, 
    ERROR_DATOS_ENVIADOS:400, 
    ERROR_AUTENTICACION:401,
    ERROR_AUTORIZACION:403
}

const ERRORES_INTERNOS={
    DATABASE:100, 
    ARGUMENTOS:200, 
    PERMISOS:300, 
    OTROS: 400
}

module.exports = { STATUS_CODES, ERRORES_INTERNOS };